# Generated by Django 3.2.16 on 2022-12-12 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('class_no', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='班号')),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('course_no', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='课程号')),
                ('course_name', models.CharField(max_length=20, verbose_name='课程名')),
            ],
        ),
        migrations.CreateModel(
            name='depts',
            fields=[
                ('dept_no', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='院系编号')),
                ('dept_name', models.CharField(max_length=20, unique=True, verbose_name='院系名')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_no', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='学号')),
                ('student_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[(1, '男'), (0, '女')], verbose_name='性别')),
                ('birth', models.DateField(verbose_name='出生年月')),
                ('native_p', models.CharField(max_length=50, verbose_name='籍贯')),
                ('class_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.classes', verbose_name='班号')),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.depts', verbose_name='院系')),
            ],
        ),
        migrations.CreateModel(
            name='gradeinfo',
            fields=[
                ('student_no', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='学号')),
                ('student_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('grade_avg', models.FloatField(null=True, verbose_name='平均成绩')),
                ('class_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.classes', verbose_name='班号')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='dept_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.depts', verbose_name='院系'),
        ),
        migrations.CreateModel(
            name='change',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('change_note', models.CharField(max_length=20, verbose_name='变更情况')),
                ('change_time', models.DateTimeField(verbose_name='记录时间')),
                ('change_mage', models.CharField(max_length=50, null=True, verbose_name='详情描述')),
                ('student_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='学生学号')),
            ],
        ),
        migrations.CreateModel(
            name='sc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(verbose_name='成绩')),
                ('course_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.courses', verbose_name='课程号')),
                ('student_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='学号')),
            ],
            options={
                'unique_together': {('student_no', 'course_no')},
            },
        ),
    ]
