# Generated by Django 3.2.16 on 2022-12-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradeinfo',
            options={'managed': False},
        ),
    ]
