# Generated by Django 3.2.16 on 2022-12-14 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_gradeinfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dept_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.depts', verbose_name='院系编号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=2, verbose_name='性别'),
        ),
        migrations.AlterModelTable(
            name='gradeinfo',
            table='student_grade_view',
        ),
    ]
