# Generated by Django 3.2.16 on 2022-12-14 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20221214_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dept_name',
            new_name='dept_no',
        ),
    ]
