# Generated by Django 3.2.16 on 2022-12-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_dept_name_student_dept_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='记录编号'),
        ),
    ]
