# Generated by Django 3.2.16 on 2022-12-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_change_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号'),
        ),
    ]
