# Generated by Django 3.2.16 on 2022-12-14 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_change_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='student_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student', verbose_name='学生学号'),
        ),
    ]
