# Generated by Django 3.2.16 on 2022-12-14 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_change_student_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='scinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=8, verbose_name='学号')),
                ('course_no', models.CharField(max_length=4, verbose_name='课程号')),
                ('course_name', models.CharField(max_length=20, verbose_name='课程名')),
                ('grade', models.FloatField(verbose_name='成绩')),
            ],
            options={
                'db_table': 'student_sc_view',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='sc',
            name='course_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.courses', verbose_name='课程号'),
        ),
    ]
