# Generated by Django 3.2.16 on 2022-12-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20221214_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scinfo',
            options={},
        ),
    ]
