# Generated by Django 3.2.16 on 2022-12-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_scinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scinfo',
            options={'managed': False},
        ),
    ]
